In [41]:
import numpy as np
from scipy.stats import poisson
#finding mean
samples = [5, 10, 100, 1000, 10**5]
p_lambda = 5
sample_5,sample_10,sample_100,sample_1000,sample_100000 = [],[],[],[],[]

for i in range(5):
    sample_5.append(poisson.rvs(p_lambda, size=5))
    sample_10.append(poisson.rvs(p_lambda, size=10))
    sample_100.append(poisson.rvs(p_lambda, size=100))
    sample_1000.append(poisson.rvs(p_lambda, size=1000))
    sample_100000.append(poisson.rvs(p_lambda, size=100000))


def middle(x):
    for i in range(len(x)):
        res = np.mean(x[i])
        print('Mean for sample_{}-{} is {}'.format(len(x[1]),i,res))
middle(sample_5)
print('Sample_5:')
for i in sample_5:
    print(i)
middle(sample_10)
print('Sample_10:')
for i in sample_10:
    print(i)
middle(sample_100)
middle(sample_1000)
middle(sample_100000)

Mean for sample_5-0 is 6.4
Mean for sample_5-1 is 4.6
Mean for sample_5-2 is 5.8
Mean for sample_5-3 is 5.0
Mean for sample_5-4 is 5.8
Sample_5:
[5 6 7 9 5]
[5 6 4 4 4]
[10  6  8  1  4]
[ 5  4 10  4  2]
[4 5 6 8 6]
Mean for sample_10-0 is 5.4
Mean for sample_10-1 is 5.6
Mean for sample_10-2 is 5.2
Mean for sample_10-3 is 6.1
Mean for sample_10-4 is 5.1
Sample_10:
[ 6  3  3  8  4  4  3  5 10  8]
[9 8 3 5 5 5 5 5 5 6]
[7 8 5 5 5 6 3 2 6 5]
[ 6  5 11  5  4  4  8  4  8  6]
[ 6  6  4  7  5  1 10  5  4  3]
Mean for sample_100-0 is 5.09
Mean for sample_100-1 is 4.84
Mean for sample_100-2 is 4.9
Mean for sample_100-3 is 5.16
Mean for sample_100-4 is 5.11
Mean for sample_1000-0 is 4.941
Mean for sample_1000-1 is 4.946
Mean for sample_1000-2 is 5.045
Mean for sample_1000-3 is 4.988
Mean for sample_1000-4 is 4.937
Mean for sample_100000-0 is 4.99706
Mean for sample_100000-1 is 4.99739
Mean for sample_100000-2 is 5.01146
Mean for sample_100000-3 is 4.99991
Mean for sample_100000-4 is 4.99372


In [31]:
def middle_1(x):
    return np.mean(x)

In [35]:
#finding var_mean
def var_mean(y):
    pp = []
    for i in range(len(y)):
        s = 0
        for j in range(len(y[i])):
            s+=(y[i][j]-middle_1(y[i]))**2
        pp.append(s/len(y[i]))
    return np.round(pp,3)

In [43]:
print(var_mean(sample_5),'sample_5')
print(var_mean(sample_10),'sample_10')
print(var_mean(sample_100),'sample_100')
print(var_mean(sample_1000),'sample_1000')
print(var_mean(sample_100000),'sample_100000')



[2.24 0.64 9.76 7.2  1.76] sample_5
[5.64 2.64 2.76 4.69 5.29] sample_10
[4.642 4.594 4.03  4.494 6.018] sample_100
[5.216 5.065 4.943 5.056 5.165] sample_1000
[5.013 4.953 5.03  5.021 5.014] sample_100000


In [45]:
import numpy as np
from scipy.stats import poisson, laplace
#finding mean
samples = [5, 10, 100, 1000, 10**5]
p_lambda = 5
sample_5,sample_10,sample_100,sample_1000,sample_100000 = [],[],[],[],[]

for i in range(5):
    sample_5.append(laplace.rvs(p_lambda, size=5))
    sample_10.append(laplace.rvs(p_lambda, size=10))
    sample_100.append(laplace.rvs(p_lambda, size=100))
    sample_1000.append(laplace.rvs(p_lambda, size=1000))
    sample_100000.append(laplace.rvs(p_lambda, size=100000))


def middle(x):
    for i in range(len(x)):
        res = np.mean(x[i])
        print('Mean for sample_{}-{} is {}'.format(len(x[1]),i,res))
middle(sample_5)
print('Sample_5:')
for i in sample_5:
    print(i)
middle(sample_10)
print('Sample_10:')
for i in sample_10:
    print(i)
middle(sample_100)
middle(sample_1000)
middle(sample_100000)

Mean for sample_5-0 is 5.323129086347488
Mean for sample_5-1 is 5.072310532628606
Mean for sample_5-2 is 4.605926815000022
Mean for sample_5-3 is 6.173585757321186
Mean for sample_5-4 is 5.326721998222662
Sample_5:
[3.31984428 5.76660291 5.63071863 6.104051   5.79442861]
[5.76662153 6.74412311 7.34859686 4.62465771 0.87755346]
[5.02862784 4.78786064 2.83184038 5.36520391 5.01610131]
[4.5289372  6.96813212 3.7073814  6.16627731 9.49720075]
[4.48788657 4.83093241 7.18565682 5.87030324 4.25883095]
Mean for sample_10-0 is 5.031810409002863
Mean for sample_10-1 is 5.136918746981531
Mean for sample_10-2 is 4.5429149552410015
Mean for sample_10-3 is 4.887534471698774
Mean for sample_10-4 is 5.376532216599213
Sample_10:
[4.47185716 8.8957439  4.94146946 3.70985033 4.20063234 3.83089616
 7.3859202  4.71188536 3.02500636 5.14484284]
[5.49617241 3.60206932 4.59703293 2.96128007 3.60968766 5.46568541
 6.49825493 4.64328889 6.21839249 8.27732336]
[5.31794792 5.91946578 5.13263359 4.04666787 4.86995

In [46]:
print(var_mean(sample_5),'sample_5')
print(var_mean(sample_10),'sample_10')
print(var_mean(sample_100),'sample_100')
print(var_mean(sample_1000),'sample_1000')
print(var_mean(sample_100000),'sample_100000')



[1.027 5.251 0.821 4.093 1.168] sample_5
[2.882 2.308 0.688 2.497 1.995] sample_10
[1.299 1.55  2.349 1.546 2.149] sample_100
[1.927 1.971 2.324 1.781 2.01 ] sample_1000
[2.011 2.015 1.997 1.994 2.015] sample_100000
