In [14]:
import numpy as np
from scipy.stats import poisson
#finding mean
samples = [5, 10, 100, 1000, 10**5]
p_lambda = 5
sample_5,sample_10,sample_100,sample_1000,sample_100000 = [],[],[],[],[]

for i in range(5):
    sample_5.append(poisson.rvs(p_lambda, size=5))
    sample_10.append(poisson.rvs(p_lambda, size=10))
    sample_100.append(poisson.rvs(p_lambda, size=100))
    sample_1000.append(poisson.rvs(p_lambda, size=1000))
    sample_100000.append(poisson.rvs(p_lambda, size=100000))


def middle(x):
    for i in range(len(x)):
        res = np.mean(x[i])
        print('Mean for sample_{}-{} is {}'.format(len(x[1]),i,res))
middle(sample_5)
for i in sample_5:
    print(i)
middle(sample_10)
for i in sample_10:
    print(i)
middle(sample_100)
middle(sample_1000)
middle(sample_100000)

Mean for sample_5-0 is 5.2
Mean for sample_5-1 is 4.6
Mean for sample_5-2 is 6.4
Mean for sample_5-3 is 5.6
Mean for sample_5-4 is 5.8
[3 6 8 3 6]
[ 2  6 10  3  2]
[ 6 11  4  8  3]
[6 4 5 7 6]
[ 2 10  2  7  8]
Mean for sample_10-0 is 5.9
Mean for sample_10-1 is 5.1
Mean for sample_10-2 is 4.6
Mean for sample_10-3 is 5.3
Mean for sample_10-4 is 4.7
[5 2 5 9 8 5 8 9 6 2]
[7 5 7 5 7 1 4 6 5 4]
[2 2 3 7 6 5 8 6 3 4]
[ 4  5  2  7  0  1 16  3  7  8]
[7 5 4 4 5 6 6 1 5 4]
Mean for sample_100-0 is 5.15
Mean for sample_100-1 is 5.08
Mean for sample_100-2 is 4.56
Mean for sample_100-3 is 5.07
Mean for sample_100-4 is 4.83
Mean for sample_1000-0 is 5.001
Mean for sample_1000-1 is 4.968
Mean for sample_1000-2 is 4.93
Mean for sample_1000-3 is 5.118
Mean for sample_1000-4 is 5.098
Mean for sample_100000-0 is 4.99665
Mean for sample_100000-1 is 5.00316
Mean for sample_100000-2 is 4.99951
Mean for sample_100000-3 is 4.99449
Mean for sample_100000-4 is 5.01004


In [31]:
def middle_1(x):
    return np.mean(x)

In [35]:
#finding var_mean
def var_mean(y):
    pp = []
    for i in range(len(y)):
        s = 0
        for j in range(len(y[i])):
            s+=(y[i][j]-middle_1(y[i]))**2
        pp.append(s/len(y[i]))
    return np.round(pp,3)

In [36]:
var_mean(sample_5)

array([ 3.76,  9.44,  8.24,  1.04, 10.56])

In [37]:
var_mean(sample_10)

array([ 6.09,  3.09,  4.04, 19.21,  2.41])

In [38]:
var_mean(sample_100)

array([5.928, 5.794, 4.106, 5.145, 4.781])

In [39]:
var_mean(sample_1000)

array([4.637, 4.919, 4.943, 5.164, 5.064])

In [40]:
var_mean(sample_100000)

array([4.955, 4.987, 4.989, 5.015, 4.974])